Add kernelfactory.canonical.com to releases page
canonical/webteam.canonical.com pull request #156
Opened 2023-05-19 18:00 UTC by pedoch

# Done

Add kernelfactory.canonical.com to the releases page

2023-05-19 18:00 UTC, webteam-app commented
Demo starting at https://webteam-canonical-com-156.demos.haus

2023-05-19 20:51 UTC, petesfrench approved these changes
LGTM

2023-05-21 12:12 UTC, anthonydillon requested changes
LGTM one comment on the code

2023-05-21 12:12 UTC, anthonydillon commented on webapp/releases.py
> +        "repository": "canonical-web-and-design/kernelfactory.canonical.com",
Isn't this `canonical` org now?

2023-05-24 09:21 UTC, pedoch commented
Hi @anthonydillon, I've changed the GitHub organization name, could you take a look when you can?

2023-05-24 09:31 UTC, anthonydillon approved these changes
LGTM :+1:

2023-05-24 09:32 UTC, merged